# Generated by Django 4.2 on 2023-11-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_section', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('message', models.CharField(blank=True, default=None, max_length=10000, null=True)),
                ('comment', models.CharField(blank=True, default=None, max_length=5000, null=True)),
            ],
        ),
    ]
